### ISSUE TITLE
Investigate order of Browse by People -> Sort by Count

### ISSUE THREAD

**Issue by erinchambers** [CDRH/family_letters#179]
On the Browse by People page (https://cdrhrailsdev.unl.edu/family-letters/en/browse/person.name), the default sort **Sort by Count (most first)** isn't actually in descending numerical order

For example: 
![Screenshot 2024-11-25 at 3 43 00 PM](https://github.com/user-attachments/assets/91e0a87d-ab85-41dc-ad9d-a03bb98f00f8)

**Sort by Count (least first)** exhibits the same problem, just in reverse.

**Comment by wkdewey** [comment]
It is working for me in my local environment.

**Comment by wkdewey** [comment]
I see now that it is out of order. This is the order that it is coming out of Elasticsearch from the query that says sort by doc_count. There is a discrepancy between counts because of nested aggregations. It is sorting on the base `doc_count` , but the real count (and the one displayed on the side) is in `field_to_item.doc_count` and the result is out of order relative to that field.
I would either need to change the query to Elasticsearch or re-sort the items in the API app.

**Comment by wkdewey** [comment]
I figure out how to change the Elasticsearch query so it sorts nested fields properly, when sorting by count.
